Putting CC: Tweaked Mixins in Common
ValkyrienSkies/Valkyrien-Skies-2 pull request #1046
Opened 2024-12-30 00:01 UTC by TechTastic

Since CC: Tweaked 1.19.4+ are now multiloader, all classes that were Mixin'd into can now be moved into Common as well as the dependency

I also updated all Mixins to the improved API versions from `1.18.2/main`

2024-12-30 06:50 UTC, TechTastic commented
Apparently Forge is broken? IDK how that has happened as it doesnt give me a useable error
![image](https://github.com/user-attachments/assets/3397b1ca-eac8-4906-b6de-f858a0a759e2)

2025-01-01 19:02 UTC, zyxkad requested changes

2025-01-01 19:02 UTC, zyxkad commented on common/src/main/java/org/valkyrienskies/mod/mixin/mod_compat/cc_tweaked/MixinTurtleMoveCommand.java
> +                    .anyMatch(BlockState::isAir);
Please follow #1051

2025-01-20 04:14 UTC, TechTastic commented on common/src/main/java/org/valkyrienskies/mod/mixin/mod_compat/cc_tweaked/MixinTurtleMoveCommand.java
> +                    .anyMatch(BlockState::isAir);
Ended up re-implementing the stream and the check another way as explained in that PR

2025-01-20 04:30 UTC, TechTastic commented
> Apparently Forge is broken? IDK how that has happened as it doesnt give me a useable error ![image](https://private-user-images.githubusercontent.com/74630543/399231546-3397b1ca-eac8-4906-b6de-f858a0a759e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzczNDY3MjgsIm5iZiI6MTczNzM0NjQyOCwicGF0aCI6Ii83NDYzMDU0My8zOTkyMzE1NDYtMzM5N2IxY2EtZWFjOC00OTA2LWI2ZGUtZjg1OGEwYTc1OWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIwVDA0MTM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNjBmZDVmNzgzMzFhOTdmMGViMzBiNzZhNmQ2YTY1NzBlMTE0ZTdkZDNiMDU5NDdiMGYwOTNkYzIxNzgxNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KWRNvVd2PFgHW_BAuIp7m6TQNzYb_8HeS80ndY8luZk)

going back to `1.20.1/main` it seems Forge has been broken so it wasnt me who broke it

2025-01-20 14:35 UTC, TechTastic commented
Ok, its ready to merge @Rubydesic 

every test works outside of changing the config for `canTurtlesLeaveScaledShips` but thats a config usse and the test its used for does work

2025-01-20 15:39 UTC, TechTastic commented
hmm... idk why that test failed...

2025-01-21 00:00 UTC, StewStrong approved these changes

2025-01-21 00:01 UTC, merged