Ship API
ValkyrienSkies/Valkyrien-Skies-2 pull request #59
Opened 2022-06-09 21:25 UTC by ewoudje

Main PR: https://github.com/ValkyrienSkies/vs-core/pull/11

This includes a minecraft extension of ShipProvider specific for block entities
And also a kotlin util for ship data management

2022-06-26 11:04 UTC, StewStrong commented
Looks pretty epic! Though, waiting on Ruby's thoughts before merging.

2022-06-26 19:07 UTC, Rubydesic requested changes

2022-06-26 19:07 UTC, Rubydesic commented on common/src/main/kotlin/org/valkyrienskies/mod/api/ShipFields.kt
> +package org.valkyrienskies.mod.api
This entire file should be in vs-core

2022-06-26 19:07 UTC, Rubydesic commented on common/src/main/kotlin/org/valkyrienskies/mod/api/BlockEntityShipProvider.kt
> +    fun shipChange(newPos: BlockPos, newLevel: Level, newShip: ShipObject) {}
maybe name it 'onShipChange' to indicate it's meant to be called by VS and not by the addon.

2022-07-02 03:50 UTC, Rubydesic approved these changes

2022-07-05 07:26 UTC, merged